---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
  - name: Get all network device info for this family - switches
    cisco.dnac.network_device_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      family: "Switches and Hubs"
    register: result

  - name: Json Query
    set_fact:
      hostname_id:
        "{{ result.dnac_response | json_query('response[*].{hostname: hostname, id: id}') }}"

  - name: Show Json Query
    debug:
      var: hostname_id
    
  - name: SAVE config to file
    copy:
        content: "{{ output_router.stdout[0] }}"
        dest: "/home/ubuntu/cisco-backups/show_run_{{ inventory_hostname }}.txt"
